fix: issue-317
prettier/plugin-pug pull request #318
Opened 2021-12-06 21:50 UTC by shadowgate15

closes #317

2021-12-07 07:35 UTC, Shinigami92 requested changes
Tested it against my codebase and it still toggles the classes back and forth.

You could create a simple example project locally and then use the formatter twice.
If you already have a project, then use something like this in your `package.json` 

`"@prettier/plugin-pug": "link:../../../OpenSource/Shinigami92/plugin-pug"`
Needs to be the relative path to your project clone.
Then clean node_modules and reinstall your dependencies with e.g. `yarn`.
Then you can test it like it is a normal dependency. You need to run `pnpm run build` in your clone.

2021-12-07 07:39 UTC, Shinigami92 commented on tests/issues/issue-317/issue-317.test.ts
> +			pugSortAttributesBeginning: [
I think you can remove this huge block. I mostly try to shrink the config for the tests down to the real problem, so only the necessary part is left over. Then you can also remove the "known-words" from eslint again, due to these are really only project specific :thinking: 
We could think about to run spellcheck only on `src`, but on the other side it's nice to have everywhere.

2021-12-08 08:33 UTC, Shinigami92 requested changes
```pug
v-row(no-gutters)
  v-col(cols="12")
    a.text-body-2.d-inline.mr-4(
      v-for="variable in variables",
      :key="variable",
      v-text="`$\\{${variable}}`",
      @click="copyToClipboard(variable)"
    )
```

became

```pug
v-row(no-gutters)
  v-col(cols="12")
    a(
      v-for="variable in variables",
      :key="variable",
      v-text="`$\\{${variable}}`"
    ).text-body-2.d-inline.mr-4@click="copyToClipboard(variable)"
```

😬

`@click="copyToClipboard(variable)"` should still be in the attributes

2021-12-08 08:36 UTC, Shinigami92 commented
I assume it's a problem with a regex pattern somewhere or so, because `:something` and `@something` (Vue event and expression bindings are not taken into account)

I'm a bit afraid of if this also breaks for Angular bindings with `(something)` and `[something]` syntax

2021-12-08 15:56 UTC, shadowgate15 commented
that is so weird because it works in the test.

https://github.com/prettier/plugin-pug/pull/318/files#diff-d49848e1889ef6546b7cc9120823686595638031bcf5c2392064b8b0d1437979R9

2021-12-08 19:08 UTC, Shinigami92 commented
Okay, I could try add a test later on... And I think about to release a beta version so you can test it and see all the junky jittering when using this functionally.
May have time tomorrow for that.

2021-12-09 15:41 UTC, shadowgate15 commented
jittering?

I have it setup as a linked dep on some of my pug projects and haven't seen that, since this fix. but they are all vanilla js not vue or angular.

2021-12-09 16:34 UTC, Shinigami92 commented
> jittering?
> 
> I have it setup as a linked dep on some of my pug projects and haven't seen that, since this fix. but they are all vanilla js not vue or angular.

Could you test it with an attribute that starts with an `@` or `:`?

2021-12-09 16:38 UTC, shadowgate15 commented
it's in the written test already and passes. and it worked in my projects. no jittering.

2021-12-09 16:39 UTC, Shinigami92 commented
> it's in the written test already and passes. and it worked in my projects. no jittering.

Okay, need to check it again
Hope I have time this evening

2021-12-09 17:41 UTC, Shinigami92 commented
It's my `pugSortAttributesEnd: ['^@click'],`! :eyes: 

So it has interference with the `pugSortAttributesEnd` (and I assume also with `pugSortAttributesBeginning`) option.
Could you add a further test to it? Or at least it should be sufficient to add `pugSortAttributesEnd: ['^@click'],` before the `pugClassLocation`.

2021-12-09 17:41 UTC, Shinigami92 commented on tests/issues/issue-317/issue-317.test.ts
> +			pugClassLocation: 'after-attributes'
```suggestion
			pugSortAttributesEnd: ['^@click'],
			pugClassLocation: 'after-attributes'
```

2021-12-09 19:44 UTC, shadowgate15 commented
yep that was the cause working on it now.

2021-12-09 21:10 UTC, shadowgate15 commented
that should do it. Let me know if you find any other edge cases.

2021-12-09 22:14 UTC, Shinigami92 commented
It works :tada: 

Only a little not-finished on first run with exact `printWidth`

After first run:

```pug
//- some other stuff
                  div(
                    v-t="'entity-management.entity-group.crud.entity-types-txt'"
                  ).text-body-2.text--secondary.mb-2.mt-4
```

After second run:

```pug
                  div(v-t="'entity-management.entity-group.crud.entity-types-txt'").text-body-2.text--secondary.mb-2.mt-4
```

But this is now 121 cols long, so exactly one of with `printWidth: 120` :thinking: 

I assume it has something to do with `this.currentLineLength`.
Would you like to tackle this also? If not and you are just satisfied, I'm also okay to merge and release it.

2021-12-09 22:26 UTC, shadowgate15 commented
I think I know where it is coming from. I’ll see if I can resolve it.

2021-12-09 22:29 UTC, Shinigami92 commented
Thank you, I will say good night for today, will read you tomorrow :)

2021-12-10 16:01 UTC, shadowgate15 commented
@Shinigami92 that should fix that problem and give an accurate count now.

2021-12-11 10:42 UTC, Shinigami92 approved these changes

2021-12-11 10:42 UTC, merged

2021-12-11 10:43 UTC, Shinigami92 commented
@shadowgate15 You can now delete your fork and directly checkout this repo.
When then creating a PR, I can more easily work together with you on that branch :slightly_smiling_face: 
You have write access, but you cannot commit directly to main branch, only custom branches/PRs